### ISSUE TITLE
Add Youtube Data API v3 support

### ISSUE THREAD

**Issue by Chromeroni** [Chromeroni/Hera-Chatbot#2]
Maven:
```
<dependency>
      <groupId>com.google.apis</groupId>  
      <artifactId>google-api-services-youtube</artifactId>  
      <version>v3-rev189-1.23.0</version>  
</dependency>
```

This enables the use of various Youtube functionalities such as searching for videos / playlists / channels via querry, or even commenting on other videos.

<h5>Usage for Hera</h5>

Ability to search for specific youtube videos using the user provided parameters. Afterwards the top search result can be added to the music queue.
 
More information about Youtube Data API v3 search list functionality: https://developers.google.com/youtube/v3/docs/search/list

**Comment by Chromeroni** [comment]
Helpful code sample: https://github.com/youtube/api-samples/blob/master/java/src/main/java/com/google/api/services/samples/youtube/cmdline/data/Search.java

**Comment by Pacmens** [comment]
implemented tested and pushed on developer
