### ISSUE TITLE
Add Music Functionality

### ISSUE THREAD

**Issue by Chromeroni** [Chromeroni/Hera-Chatbot#3]
Add functionality to stream music through Hera.

<h4>Command list:</h4>

* **play | p**  
Queues a through parameters provided song. Parameter can either be a URL or a few keywords to search on Youtube (#2 Add Youtube Data API v3 support).
* **queue**  
Shows the all songs in the current queue.
* **lq**  
Start at the beginning of the queue if the last song was played.
* **remove | rm**  
Remove a song from the queue. The song to remove is determined through a song ID which is provided as a parameter.
* **skip**  
Skip the currently playing song and move on to the next song.
* **move**  
Move a song onto a specific index in the queue. Which song and which position are provided through parameters.
* **volume**  
Set the volume of the bot. Volume-value is determined through a provided parameter.

**Comment by Chromeroni** [comment]
Suggested library: lavaPlayer https://github.com/sedmelluq/lavaplayer

LavaPlayer is a java library written for discord bots. It simplifys the implementation of the music function through the Discord 4 Java library and results in higher quality audio output. 
The use of lavaPlayer is recommended by austinv11, the creator of Discord 4 Java.

Maven dependency:
```
<repositories>
  <repository>
    <id>central</id>
    <name>bintray</name>
    <url>http://jcenter.bintray.com</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>com.sedmelluq</groupId>
    <artifactId>lavaplayer</artifactId>
    <version>1.2.45</version>
  </dependency>
</dependencies>
```

**Comment by Chromeroni** [comment]
<h3>TODO</h3>
* lq
* remove
* skip
* move

**Comment by Pacmens** [comment]
mostly done

TODO 

*testing

**Comment by Pacmens** [comment]
tested 
TODO move

**Comment by Chromeroni** [comment]
Implemented and tested all requested functions.
