### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by Pacmens** [Chromeroni/Hera-Chatbot#7]
<h3>Refactoring changes<h3>
<ul>
<li>only one message recived event</li>
<li>method name changes</li>
<li>package changes</li>
<li>create singeltons</li>
</ul>

**Comment by Pacmens** [comment]
make enum names singular

**Comment by Pacmens** [comment]
singletons done
method name changes done
only one message recived event done

**Comment by Chromeroni** [comment]
Update gitignore file with these settings: https://gist.github.com/chhh/4961200
